# Generated by Django 4.2 on 2026-03-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('external_id', models.CharField(max_length=255)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='BookingSystem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField()),
                ('credentials', models.JSONField(default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('Error', 'Error')], db_index=True, default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('external_id', models.CharField(max_length=255)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('booking_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app_booking.bookingsystem')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('external_id', models.CharField(max_length=255)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('booking_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='app_booking.bookingsystem')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('external_id', models.CharField(max_length=255)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('booking_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='app_booking.bookingsystem')),
            ],
        ),
        migrations.AddIndex(
            model_name='bookingsystem',
            index=models.Index(fields=['name'], name='app_booking_name_0a5686_idx'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='booking_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app_booking.bookingsystem'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='app_booking.customer'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='app_booking.provider'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='app_booking.service'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['booking_system', 'name'], name='app_booking_booking_7d30ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('booking_system', 'external_id'), name='uniq_service_external_id_per_system'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['booking_system', 'last_name', 'first_name'], name='app_booking_booking_abb5e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(fields=('booking_system', 'external_id'), name='uniq_provider_external_id_per_system'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['booking_system', 'last_name', 'first_name'], name='app_booking_booking_a59990_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('booking_system', 'external_id'), name='uniq_customer_external_id_per_system'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['booking_system', 'start_time'], name='app_booking_booking_8187c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('booking_system', 'external_id'), name='uniq_appointment_external_id_per_system'),
        ),
    ]
