# Generated by Django 4.2 on 2026-03-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsystem',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bookingsystem',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('error', 'Error')], db_index=True, default='pending', max_length=20),
        ),
    ]
