# Generated by ChatGPT for seeding booking data.
# The code is generated to populate the database with sample data for testing and development purposes.

import random
from datetime import timedelta

from django.core.management.base import BaseCommand
from django.utils import timezone

from app_booking.models import (
    BookingSystem,
    Provider,
    Customer,
    Service,
    Appointment,
)


class Command(BaseCommand):
    help = "Populate booking system with sample data"

    def handle(self, *args, **kwargs):

        # ---- Booking System ----
        booking_system, created = BookingSystem.objects.get_or_create(
            name="Demo Booking System",
            defaults={
                "base_url": "https://demo-booking.local",
                "credentials": {
                    "username": "demo",
                    "password": "demo123",
                },
            },
        )

        self.stdout.write(self.style.SUCCESS(f"BookingSystem: {booking_system.name}"))

        # ---- Providers ----
        providers = []
        for i in range(5):
            provider, _ = Provider.objects.get_or_create(
                booking_system=booking_system,
                external_id=f"prov-{i}",
                defaults={
                    "first_name": f"Provider{i}",
                    "last_name": "Smith",
                    "email": f"provider{i}@example.com",
                    "phone": f"+88017000000{i}",
                },
            )
            providers.append(provider)

        self.stdout.write(self.style.SUCCESS(f"{len(providers)} providers created"))

        # ---- Customers ----
        customers = []
        for i in range(20):
            customer, _ = Customer.objects.get_or_create(
                booking_system=booking_system,
                external_id=f"cust-{i}",
                defaults={
                    "first_name": f"Customer{i}",
                    "last_name": "Doe",
                    "email": f"customer{i}@example.com",
                    "phone": f"+88018000000{i}",
                },
            )
            customers.append(customer)

        self.stdout.write(self.style.SUCCESS(f"{len(customers)} customers created"))

        # ---- Services ----
        services_data = [
            ("Consultation", 30, 50),
            ("Therapy Session", 60, 120),
            ("Haircut", 20, 30),
        ]

        services = []
        for i, (name, duration, price) in enumerate(services_data):
            service, _ = Service.objects.get_or_create(
                booking_system=booking_system,
                external_id=f"svc-{i}",
                defaults={
                    "name": name,
                    "duration_minutes": duration,
                    "price": price,
                    "currency": "USD",
                },
            )
            services.append(service)

        self.stdout.write(self.style.SUCCESS(f"{len(services)} services created"))

        # ---- Appointments ----
        appointments_created = 0

        for i in range(30):

            provider = random.choice(providers)
            customer = random.choice(customers)
            service = random.choice(services)

            start_time = timezone.now() + timedelta(days=random.randint(0, 10))
            end_time = start_time + timedelta(minutes=service.duration_minutes)

            Appointment.objects.get_or_create(
                booking_system=booking_system,
                external_id=f"appt-{i}",
                defaults={
                    "provider": provider,
                    "customer": customer,
                    "service": service,
                    "start_time": start_time,
                    "end_time": end_time,
                    "status": random.choice(["confirmed", "cancelled", "pending"]),
                    "location": "Main Office",
                },
            )

            appointments_created += 1

        self.stdout.write(
            self.style.SUCCESS(f"{appointments_created} appointments created")
        )

        self.stdout.write(self.style.SUCCESS("Database seeding completed!"))
